import type { Claim, CoverageAssessment } from "./types";
import { listChunksForOrg } from "./repo";
import { searchChunks } from "./retrieval";

/**
 * Real retrieval when a tenant has uploaded policy documents (via
 * /api/documents) — TF-IDF search over the actual uploaded text, see
 * retrieval.ts. Falls back to a small sample-clause library only when no
 * documents exist for the org yet, so the demo still shows *something*
 * before you've uploaded a real policy PDF.
 *
 * What's still a stand-in even with real documents uploaded: turning the
 * retrieved passages into a fluent "likely covered / needs review"
 * narrative. That step is templated here rather than generated by a
 * hosted LLM, because a live LLM call needs a paid API key, which
 * conflicts with running this at $0. The retrieval itself — finding which
 * passages are actually relevant to this claim — is real and does the
 * hard part; text generation on top of already-retrieved passages is the
 * cheap part to add later (see docs/02-architecture-decisions.md).
 */

const SAMPLE_CLAUSES: Record<
  string,
  { clauses: string[]; exclusion: string; reasoning: string; verdict: CoverageAssessment["verdict"] }
> = {
  water_damage: {
    clauses: ["Section 4.2 — Sudden and Accidental Water Discharge", "Section 7.1 — Interior Property Damage"],
    exclusion: "Section 4.5 — Gradual Leakage or Seepage Exclusion may apply if onset predates policy period",
    reasoning:
      "No policy document uploaded for this tenant yet, so this is drawn from a small sample clause library, not this claim's actual policy. Upload a policy PDF in Onboarding to get a real, retrieval-backed answer.",
    verdict: "needs_review",
  },
  fire: {
    clauses: ["Section 3.1 — Fire and Lightning", "Section 7.3 — Smoke Damage to Contents"],
    exclusion: "Section 3.4 — Intentional Acts Exclusion",
    reasoning:
      "No policy document uploaded for this tenant yet — sample library only. Upload a policy PDF to get a retrieval-backed answer grounded in the real document.",
    verdict: "needs_review",
  },
};

export function assessCoverage(claim: Claim): CoverageAssessment {
  const chunks = listChunksForOrg(claim.organization_id);

  if (chunks.length > 0) {
    const query = `${claim.claim_type.replace(/_/g, " ")} claim, estimated loss ${claim.estimated_loss}, ${claim.policyholder_name}`;
    const results = searchChunks(query, chunks, 3);

    if (results.length > 0) {
      const bestScore = results[0].score;
      const lowerText = results.map((r) => r.content.toLowerCase()).join(" ");
      const mentionsExclusion = lowerText.includes("exclu");
      const verdict: CoverageAssessment["verdict"] =
        bestScore > 0.35 ? (mentionsExclusion ? "needs_review" : "likely_covered") : "needs_review";

      return {
        verdict,
        relevantClauses: results.map(
          (r) => `${r.filename} — "${r.content.slice(0, 90).trim()}…" (match ${(r.score * 100).toFixed(0)}%)`
        ),
        exclusion: mentionsExclusion
          ? "Retrieved passages mention an exclusion — adjuster should confirm which one applies before finalizing."
          : null,
        deductible: 2500,
        coverageLimit: claim.estimated_loss > 60000 ? 250000 : 100000,
        confidence: Math.min(0.95, Math.max(0.35, bestScore)),
        reasoning: `Retrieved from ${results.length} matching passage(s) in the uploaded policy document(s) via TF-IDF similarity search (real retrieval, not a template) — see the matched excerpts above.`,
      };
    }
  }

  const entry =
    SAMPLE_CLAUSES[claim.claim_type] ??
    {
      clauses: ["Section 1.1 — General Coverage Grant"],
      exclusion: "No specific exclusion matched — manual policy review recommended",
      reasoning: "No policy document uploaded, and this claim type isn't in the small sample library either. Upload a policy PDF for a real answer.",
      verdict: "needs_review" as const,
    };

  return {
    verdict: entry.verdict,
    relevantClauses: entry.clauses,
    exclusion: entry.exclusion,
    deductible: 2500,
    coverageLimit: claim.estimated_loss > 60000 ? 250000 : 100000,
    confidence: 0.35,
    reasoning: entry.reasoning,
  };
}
