import type { Claim, ClaimEvent, Organization, Rule } from "./types";

export const ORGANIZATIONS: Organization[] = [
  {
    id: "org_acme",
    name: "Acme Insurance",
    line_of_business: "Commercial Property",
    sla_hours: 48,
    fraud_threshold: 0.75,
    high_value_threshold: 25000,
    required_documents: ["Invoice", "Photos", "Policy", "Proof of Loss"],
    brand_color: "#17726A",
    claims_source: "CSV upload",
    policy_source: "JSON API",
  },
  {
    id: "org_voyage",
    name: "Voyage Travel Insurance",
    line_of_business: "Travel",
    sla_hours: 24,
    fraud_threshold: 0.65,
    high_value_threshold: 10000,
    required_documents: ["Booking Confirmation", "Receipt", "Medical Evidence"],
    brand_color: "#C8790E",
    claims_source: "Webhook",
    policy_source: "Legacy XML feed",
  },
];

export const RULES: Rule[] = [
  {
    id: "rule_acme_high_value",
    organization_id: "org_acme",
    name: "High Value Claim",
    conditions: [{ field: "estimated_loss", operator: ">", value: 25000 }],
    actions: ["assign_senior_adjuster", "require_human_review", "priority_high"],
    priority: 1,
    enabled: true,
  },
  {
    id: "rule_acme_fraud",
    organization_id: "org_acme",
    name: "Potential Fraud",
    conditions: [{ field: "fraud_score", operator: ">", value: 0.75 }],
    actions: ["route_to_siu", "require_human_review"],
    priority: 0,
    enabled: true,
  },
  {
    id: "rule_acme_docs",
    organization_id: "org_acme",
    name: "Elevated Document Anomaly",
    conditions: [{ field: "document_anomaly_score", operator: ">", value: 0.6 }],
    actions: ["request_additional_documents", "status_pending_information"],
    priority: 2,
    enabled: true,
  },
  {
    id: "rule_voyage_high_value",
    organization_id: "org_voyage",
    name: "High Value Claim",
    conditions: [{ field: "estimated_loss", operator: ">", value: 10000 }],
    actions: ["assign_senior_adjuster", "require_human_review", "priority_high"],
    priority: 1,
    enabled: true,
  },
  {
    id: "rule_voyage_fraud",
    organization_id: "org_voyage",
    name: "Potential Fraud",
    conditions: [{ field: "fraud_score", operator: ">", value: 0.65 }],
    actions: ["route_to_siu", "require_human_review"],
    priority: 0,
    enabled: true,
  },
  {
    id: "rule_voyage_new_policy",
    organization_id: "org_voyage",
    name: "New Policy Claim",
    conditions: [{ field: "days_since_policy_start", operator: "<", value: 14 }],
    actions: ["route_to_siu", "priority_high"],
    priority: 3,
    enabled: true,
  },
];

const CLAIM_TYPE_EXPECTED_LOSS: Record<string, number> = {
  water_damage: 14000,
  fire: 32000,
  theft: 6000,
  liability: 40000,
  wind_hail: 18000,
  bodily_injury: 22000,
  trip_cancellation: 3200,
  lost_baggage: 1400,
};

function claim(partial: Omit<Claim, "sla_hours"> & { sla_hours?: number }): Claim {
  const org = ORGANIZATIONS.find((o) => o.id === partial.organization_id)!;
  return { sla_hours: org.sla_hours, ...partial };
}

export const CLAIMS: Claim[] = [
  claim({
    id: "CLM-1001",
    organization_id: "org_acme",
    claim_type: "water_damage",
    policyholder_name: "Nadia Ferreira",
    policy_id: "POL-8821",
    loss_date: "2026-08-10",
    estimated_loss: 18500,
    repair_cost: 17200,
    policy_age_days: 812,
    previous_claims_count: 0,
    days_since_policy_start: 812,
    document_anomaly_score: 0.12,
    status: "in_review",
    assigned_to: "J. Alvarez",
    geography: "Texas",
    severity: "medium",
    created_at: "2026-08-21T08:32:00Z",
  }),
  claim({
    id: "CLM-1002",
    organization_id: "org_acme",
    claim_type: "fire",
    policyholder_name: "Marcus Webb",
    policy_id: "POL-4410",
    loss_date: "2026-08-18",
    estimated_loss: 87000,
    repair_cost: 81000,
    policy_age_days: 1490,
    previous_claims_count: 1,
    days_since_policy_start: 1490,
    document_anomaly_score: 0.22,
    status: "new",
    assigned_to: null,
    geography: "Texas",
    severity: "high",
    created_at: "2026-08-22T09:10:00Z",
  }),
  claim({
    id: "CLM-1003",
    organization_id: "org_acme",
    claim_type: "theft",
    policyholder_name: "Priya Nair",
    policy_id: "POL-2290",
    loss_date: "2026-08-15",
    estimated_loss: 9200,
    repair_cost: 9200,
    policy_age_days: 40,
    previous_claims_count: 3,
    days_since_policy_start: 40,
    document_anomaly_score: 0.71,
    status: "siu_review",
    assigned_to: "SIU Team",
    geography: "Ohio",
    severity: "medium",
    created_at: "2026-08-20T14:02:00Z",
  }),
  claim({
    id: "CLM-1004",
    organization_id: "org_acme",
    claim_type: "wind_hail",
    policyholder_name: "Devon Cole",
    policy_id: "POL-7712",
    loss_date: "2026-08-05",
    estimated_loss: 21000,
    repair_cost: 19800,
    policy_age_days: 260,
    previous_claims_count: 0,
    days_since_policy_start: 260,
    document_anomaly_score: 0.18,
    status: "approved",
    assigned_to: "R. Kim",
    geography: "Oklahoma",
    severity: "medium",
    created_at: "2026-08-06T11:00:00Z",
  }),
  claim({
    id: "CLM-1005",
    organization_id: "org_acme",
    claim_type: "liability",
    policyholder_name: "Chen Logistics LLC",
    policy_id: "POL-9931",
    loss_date: "2026-08-19",
    estimated_loss: 61000,
    repair_cost: 0,
    policy_age_days: 950,
    previous_claims_count: 0,
    days_since_policy_start: 950,
    document_anomaly_score: 0.09,
    status: "pending_information",
    assigned_to: "J. Alvarez",
    geography: "Texas",
    severity: "high",
    created_at: "2026-08-22T16:40:00Z",
  }),
  claim({
    id: "CLM-2001",
    organization_id: "org_voyage",
    claim_type: "trip_cancellation",
    policyholder_name: "Elena Sokolova",
    policy_id: "VPL-3301",
    loss_date: "2026-08-12",
    estimated_loss: 2900,
    repair_cost: 0,
    policy_age_days: 90,
    previous_claims_count: 0,
    days_since_policy_start: 90,
    document_anomaly_score: 0.08,
    status: "approved",
    assigned_to: "T. Osei",
    geography: "New York",
    severity: "low",
    created_at: "2026-08-13T10:15:00Z",
  }),
  claim({
    id: "CLM-2002",
    organization_id: "org_voyage",
    claim_type: "lost_baggage",
    policyholder_name: "Omar Haddad",
    policy_id: "VPL-5540",
    loss_date: "2026-08-20",
    estimated_loss: 1650,
    repair_cost: 0,
    policy_age_days: 8,
    previous_claims_count: 1,
    days_since_policy_start: 8,
    document_anomaly_score: 0.44,
    status: "siu_review",
    assigned_to: "SIU Team",
    geography: "Florida",
    severity: "low",
    created_at: "2026-08-21T07:55:00Z",
  }),
  claim({
    id: "CLM-2003",
    organization_id: "org_voyage",
    claim_type: "bodily_injury",
    policyholder_name: "Grace Adeyemi",
    policy_id: "VPL-1187",
    loss_date: "2026-08-17",
    estimated_loss: 13400,
    repair_cost: 0,
    policy_age_days: 210,
    previous_claims_count: 0,
    days_since_policy_start: 210,
    document_anomaly_score: 0.15,
    status: "in_review",
    assigned_to: "T. Osei",
    geography: "California",
    severity: "high",
    created_at: "2026-08-18T09:30:00Z",
  }),
];

export const CLAIM_EVENTS: ClaimEvent[] = [
  { id: "ev1", claim_id: "CLM-1001", timestamp: "2026-08-21T08:32:00Z", label: "FNOL received", actor: "policyholder" },
  { id: "ev2", claim_id: "CLM-1001", timestamp: "2026-08-21T08:33:00Z", label: "Documents extracted", actor: "system" },
  { id: "ev3", claim_id: "CLM-1001", timestamp: "2026-08-21T08:34:00Z", label: "Policy matched", actor: "system" },
  { id: "ev4", claim_id: "CLM-1001", timestamp: "2026-08-21T08:35:00Z", label: "Coverage analysis complete", actor: "system" },
  { id: "ev5", claim_id: "CLM-1001", timestamp: "2026-08-21T08:35:30Z", label: "Fraud score generated", actor: "system" },
  { id: "ev6", claim_id: "CLM-1001", timestamp: "2026-08-21T08:36:00Z", label: "Rule engine executed", actor: "system" },
  { id: "ev7", claim_id: "CLM-1001", timestamp: "2026-08-21T08:36:10Z", label: "Human review requested", actor: "system" },
  { id: "ev8", claim_id: "CLM-1001", timestamp: "2026-08-21T08:41:00Z", label: "Adjuster opened claim", actor: "adjuster" },
];

export function eventsForClaim(claimId: string): ClaimEvent[] {
  return CLAIM_EVENTS.filter((e) => e.claim_id === claimId);
}

export const SAMPLE_SCHEMA_MAPPING = [
  { sourceField: "customer_claim_number", targetField: "claim_id", confidence: 0.98 },
  { sourceField: "insured_name", targetField: "policyholder_name", confidence: 0.96 },
  { sourceField: "loss_date", targetField: "date_of_loss", confidence: 0.99 },
  { sourceField: "loss_type", targetField: "claim_type", confidence: 0.94 },
  { sourceField: "policy_ref", targetField: "policy_id", confidence: 0.91 },
  { sourceField: "estimated_damage", targetField: "estimated_loss", confidence: 0.89 },
];

export function expectedLossFor(claimType: string): number {
  return CLAIM_TYPE_EXPECTED_LOSS[claimType] ?? 15000;
}
